version: 2
services:

  dask-worker:
    image: drtools/code-challenge:latest
    command: dask-worker --scheduler-host dask-scheduler:8786 --ncores 2 --mem-limit 0.2
    depends_on:
      - dask-scheduler

  dask-scheduler:
    image: drtools/code-challenge:latest
    command: dask-scheduler
    ports:
      - "8786:8786"
